name: OpenWarp
main: com.lithium3141.OpenWarp.OpenWarp
author: lithium3141
version: 1.2-b@BUILD@ (rev @COMMIT@)
database: false
commands:
    warp:
        description: Manipulate warp points
        usage: /<command>
        aliases: owwarp
    top:
        description: Move to top block
        usage: /<command>
        aliases: owtop
    j:
        description: Jump to targeted block
        usage: /<command>
        aliases: owj
    jump:
        description: Jump to targeted block
        usage: /<command>
        aliases: owjump
    back:
        description: Return to previous location
        usage: /<command>
        aliases: owback
    home:
        description: Move to specified home
        usage: /<command>
        aliases: owhome
    sethome:
        description: Mark current location as home
        usage: /<command>
        aliases: owsethome
    tp:
        description: Teleport to a particular player
        usage: /<command>
        aliases: owtp
    summon:
        description: Summon a player
        usage: /<command>
        aliases: owsummon
