name: OpenWarp
main: com.lithium3141.OpenWarp.OpenWarp
author: lithium3141
version: 1.0-b@BUILD@ (rev @COMMIT@)
database: false
softdepend: [Multiverse-Core, MultiVerse]
commands:
    warp:
        description: Manipulate warp points
        usage: /<command>
    top:
        description: Move to top block
        usage: /<command>
    j:
        description: Jump to targeted block
        usage: /<command>
    jump:
        description: Jump to targeted block
        usage: /<command>
    back:
        description: Return to previous location
        usage: /<command>
    home:
        description: Move to specified home
        usage: /<command>
    sethome:
        description: Mark current location as home
        usage: /<command>
