name: OpenWarp
main: com.lithium3141.OpenWarp.OpenWarp
author: lithium3141
version: 0.1-alpha
database: false
commands:
    warp:
        description: Manipulate warp points
        usage: /<command>
    top:
        description: Move to top block
        usage: /<command>
    j:
        description: Jump to targeted block
        usage: /<command>
    jump:
        description: Jump to targeted block
        usage: /<command>
    back:
        description: Return to previous location
        usage: /<command>
